# Map is divided into 'zones'. Traversal between these is tbd.
# Each zone is 5x5 (for now) and are specific areas.

zone1 = {
    'a1': {
        'name':'Home',
        'description':'This is the home you live in.',
        'solved':False,
        'up':'',
        'down':['down', 'south'],
        'left':'',
        'right':['right', 'east']},
    'a2': {
        'name':'Town Outskirts',
        'description':'The outer parts of the town.',
        'solved':False,
        'up':['up', 'north'],
        'down':['down', 'south'],
        'left':'',
        'right':['right', 'east']},
    'a3': {
        'name':'Town Plaza',
        'description':'This is the majority of the city.',
        'solved':False,
        'up':['up', 'north'],
        'down':['down', 'south'],
        'left':'',
        'right':['right', 'east']},
    'a4': {
        'name':'Town Market',
        'description':'This is the market, the local shops.',
        'solved':False,
        'up':['up', 'north'],
        'down':['down', 'south'],
        'left':'',
        'right':['right', 'east']},
    'a5': {
        'name':'',
        'description':'',
        'solved':False,
        'up':['up', 'north'],
        'down':'',
        'left':'',
        'right':['right', 'east']},
    'b1': {
        'name':'',
        'description':'',
        'solved':False,
        'up':'',
        'down':['down', 'south'],
        'left':['left', 'west'],
        'right':['right', 'east']},
    'b2': {
        'name':'',
        'description':'',
        'solved':False,
        'up':['up', 'north'],
        'down':['down', 'south'],
        'left':['left', 'west'],
        'right':['right', 'east']},
    'b3': {
        'name':'',
        'description':'',
        'solved':False,
        'up':['up', 'north'],
        'down':['down', 'south'],
        'left':['left', 'west'],
        'right':['right', 'east']},
    'b4': {
        'name':'',
        'description':'',
        'solved':False,
        'up':['up', 'north'],
        'down':['down', 'south'],
        'left':['left', 'west'],
        'right':['right', 'east']},
    'b5': {
        'name':'',
        'description':'',
        'solved':False,
        'up':['up', 'north'],
        'down':'',
        'left':['left', 'west'],
        'right':['right', 'east']},
    'c1': {
        'name':'',
        'description':'',
        'solved':False,
        'up':'',
        'down':['down', 'south'],
        'left':['left', 'west'],
        'right':['right', 'east']},
    'c2': {
        'name':'',
        'description':'',
        'solved':False,
        'up':['up', 'north'],
        'down':['down', 'south'],
        'left':['left', 'west'],
        'right':['right', 'east']},
    'c3': {
        'name':'',
        'description':'',
        'solved':False,
        'up':['up', 'north'],
        'down':['down', 'south'],
        'left':['left', 'west'],
        'right':['right', 'east']},
    'c4': {
        'name':'',
        'description':'',
        'solved':False,
        'up':['up', 'north'],
        'down':['down', 'south'],
        'left':['left', 'west'],
        'right':['right', 'east']},
    'c5': {
        'name':'',
        'description':'',
        'solved':False,
        'up':['up', 'north'],
        'down':'',
        'left':['left', 'west'],
        'right':['right', 'east']},
    'd1': {
        'name':'',
        'description':'',
        'solved':False,
        'up':'',
        'down':['down', 'south'],
        'left':['left', 'west'],
        'right':['right', 'east']},
    'd2': {
        'name':'',
        'description':'',
        'solved':False,
        'up':['up', 'north'],
        'down':['down', 'south'],
        'left':['left', 'west'],
        'right':['right', 'east']},
    'd3': {
        'name':'',
        'description':'',
        'solved':False,
        'up':['up', 'north'],
        'down':['down', 'south'],
        'left':['left', 'west'],
        'right':['right', 'east']},
    'd4': {
        'name':'',
        'description':'',
        'solved':False,
        'up':['up', 'north'],
        'down':['down', 'south'],
        'left':['left', 'west'],
        'right':['right', 'east']},
    'd5': {
        'name':'',
        'description':'',
        'solved':False,
        'up':['up', 'north'],
        'down':'',
        'left':['left', 'west'],
        'right':['right', 'east']},
    'e1': {
        'name':'',
        'description':'',
        'solved':False,
        'up':'',
        'down':['down', 'south'],
        'left':['left', 'west'],
        'right':''},
    'e2': {
        'name':'',
        'description':'',
        'solved':False,
        'up':['up', 'north'],
        'down':['down', 'south'],
        'left':['left', 'west'],
        'right':''},
    'e3': {
        'name':'',
        'description':'',
        'solved':False,
        'up':['up', 'north'],
        'down':['down', 'south'],
        'left':['left', 'west'],
        'right':''},
    'e4': {
        'name':'',
        'description':'',
        'solved':False,
        'up':['up', 'north'],
        'down':['down', 'south'],
        'left':['left', 'west'],
        'right':''},
    'e5': {
        'name':'',
        'description':'',
        'solved':False,
        'up':['up', 'north'],
        'down':'',
        'left':['left', 'west'],
        'right':''}}